### ISSUE TITLE
Not working with AutoLoad

### ISSUE THREAD

**Issue by HighSoftWare96** [cfware/fastify-babel#27]
Is there a way to make this plugin work with Fastify AutoLoad API?

**Comment by coreyfarrell** [comment]
I don't know what fastify autoload is, please share a link to documentation for this.

**Comment by coreyfarrell** [comment]
So I see the fastify-autoload module but I'm not sure how that would apply to this.  Could you please link a small demo repository showing how you expect to use autoload and let me know what you expect to happen?

**Comment by HighSoftWare96** [comment]
I'm not sure I've understand totally the functionalities of this library but I'm expecting that with the babel configuration I put once I try to use autoLoad for loading my project files before importing the files this plugin run the babel script in order to get the JS files converted.

**Comment by coreyfarrell** [comment]
I'm sorry I'm not really following what you're trying to do / what you expect do happen.  I don't think I can help further without a link to some kind of repository.
